services:

  frontend:
    build:
      context: ./frontend
    ports:
      - '8000:3000'
    volumes:
      - './frontend:/opt/app'
    environment:
      - "CI:'true'"
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - '4000:5000'
    volumes:
      - './backend:/opt/app'
    restart: always
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/opt/app/data/db
    ports:
      - '27017:27017'
    restart: always
